# 4. Numpy_2

In [2]:
import numpy as np

#### 1. 고급 배열 조작  

1.1 배열의 모양 바꾸기 

In [20]:
# reshape() : 데이터 복사하지 않고 다른 모양으로 변환함
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
arr.reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# -1을 넣으면 알아서 숫자를 맞춰준다. 
arr.reshape((5,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
# ravel() : 모든 요소를 한 줄로 만들어 반환한다. <-> flatten() : 같은 기능을 하지만 flatten은 복사본을 만든다. 
# default는 행을 기준으로 핀다. 파라미터로 f를 넣으면 열을 기준으로 핀다. 
arr.ravel()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

1.2 배열 이어붙이고 나누기

In [25]:
# concatenate() : 두 배열을 이어 붙인다. 

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [26]:
# axis = 0 :행을 기준을 쌓는다. 
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
# axis = 1 : 열을 기준으로 쌓는다.
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [28]:
# vstack() : 행으로 쌓는다. 
np.vstack((arr1,arr2)) 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
# hstack() : 열로 쌓는다. 
np.hstack((arr1,arr2))


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [30]:
# split() : 나누기 
arr = np.arange(10).reshape((5,2))
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
first, second, third = np.split(arr,[1,3]) # 1번행과 3번행을 기준으로 3개로 나누어 반환한다. 

In [32]:
first # 0번째 행

array([[0, 1]])

In [33]:
second #1번에서 2번째 행

array([[2, 3],
       [4, 5]])

In [34]:
third # 3번에서 마지막 행까지 

array([[6, 7],
       [8, 9]])

1.3 r_ and c_

In [35]:
np.r_[arr1,arr2] # 행을 기준으로 쌓는다. 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [38]:
np.c_[arr1,arr2] # 열을 기준으로 쌓는다. 

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

1.4 원소 반복하기 : repeat, tile (원본을 변화시키지 않는다.)

In [40]:
# repeat
arr = np.arange(3)
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [43]:
# 각 요소별로 반복횟수 다르게 하기 
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [45]:
# 다차원 배열 반복 
arr = np.arange(4).reshape(2,2)
arr

array([[0, 1],
       [2, 3]])

In [46]:
arr.repeat(2,axis = 0)

array([[0, 1],
       [0, 1],
       [2, 3],
       [2, 3]])

In [47]:
arr.repeat(2,axis = 1)

array([[0, 0, 1, 1],
       [2, 2, 3, 3]])

In [48]:
arr.repeat(2) # 축을 입력하지 않으면 평탄화 됨

array([0, 0, 1, 1, 2, 2, 3, 3])

In [49]:
np.tile(arr,2)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [52]:
np.tile(arr,(2,1)) #행 방향으로 2번, 열 방향으로 1번 arr을 붙인다. 즉 (2*1) 짜리 arr로 된 행렬을 만든다. 

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

1.5 fancy index : take and put

In [53]:
arr =np.arange(10) * 100

In [55]:
inds = [7,1,2,6]

In [58]:
arr.take(inds) # 해당 index만을 뽑아서 새로운 행렬을 반환한다. 

array([700, 100, 200, 600])

In [59]:
arr.put(inds,42) # 해당 index에 숫자를 넣는다. 

In [61]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [81]:
arr = np.arange(16).reshape(2,2,-1)

In [82]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [83]:
# 다차원 행렬의 경우도 열을 기준으로 뽑아서 반환한다. 
inds = [2,0,2,1]
arr.take(inds, axis=2)

array([[[ 2,  0,  2,  1],
        [ 6,  4,  6,  5]],

       [[10,  8, 10,  9],
        [14, 12, 14, 13]]])

#### 2. broadcasting 

In [3]:
# 스칼라를 합치는 경우  
arr = np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3]])
arr1 = np.array([1,1,1])
arr - arr1

array([[-1, -1, -1],
       [ 0,  0,  0],
       [ 1,  1,  1],
       [ 2,  2,  2]])

In [7]:
arr = np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3]])
arr2 = np.array([[0],
                 [1],
                 [2],
                 [3]])
arr - arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
# newaxis : 새로운 축을 만든데 사용됨
arr = np.zeros((4,4))
arr_3d = arr[:,np.newaxis,:]
print(arr_3d.shape)
arr_3d

(4, 1, 4)


array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [15]:
arr_1d = np.random.normal(size=3)
print(arr_1d.shape)
arr_1d[:,np.newaxis].shape



(3,)


(3, 1)

In [17]:
np.array([[[1,2,3],[4,5,6]]]).shape

(1, 2, 3)

In [22]:
arr = np.random.randn(3,4,5)
arr

array([[[-0.21164741,  0.21622114,  0.32536659, -0.06529872,
         -0.17981071],
        [-0.21971504, -0.15164294,  1.80067804, -0.85361432,
          1.2108049 ],
        [-0.46689212, -0.29524926,  0.83373739, -0.64345515,
         -1.45818309],
        [-1.69020779,  0.97845188,  0.3249365 , -0.79517993,
          0.60021496]],

       [[ 1.11784907,  0.31843425,  0.79811448, -0.08455201,
          0.71099733],
        [-0.33409168, -2.07886787, -0.89902782,  1.19039288,
         -1.81068334],
        [-0.92436163, -0.25277181,  2.4666089 ,  0.46694835,
          2.03062034],
        [-1.69399874,  0.23358783,  0.48348769,  0.29298116,
          1.11051669]],

       [[-0.39756801,  0.40808181, -1.21742718,  1.38692888,
         -0.74753396],
        [-1.1669646 , -1.31930737,  0.8258397 , -0.99980873,
          1.39543562],
        [-0.33814648,  1.93851764, -0.53161934, -0.92934814,
         -1.01238232],
        [-0.43628429, -0.16483941,  0.89983829, -0.13487292,
          0

In [28]:
depth_means = arr.mean(0)

In [29]:
depth_means.shape

(4, 5)