# 4. Numpy

Numpy : 단일 산술 배열 데이터를 다루는데 특화되어 있음 

In [1]:
import numpy as np 

#### ndarray 구성요소 

1. 데이터 포인터 : ram이나 메모리 맵 파일에서 데이터의 블록 
2. dtype : 배열 내에 값을 담는 고정된 크기    
3. shape : 배열의 모양을 알려주는 tuple  
4. stride : 하나의 차원을 따라 몇 바이트 이동해야 하는지 나타내는 tuple  

In [2]:
# numpy의 dtype 상속관계 알아보기 

# mro() : 어느 클래스에 상속되어 있는지 알 수 있는 method
np.float64.mro()

# issubdtype() : 첫번째가 두번째에 속해 있는지 알 수 있는 method 
ints = np.ones(10,dtype=np.uint16)
np.issubdtype(ints.dtype,np.integer)

True

#### 1. ndarray 속성

In [3]:
data = np.random.rand(4,3)
data

array([[0.33122257, 0.39901399, 0.42326359],
       [0.23666968, 0.73290394, 0.92419143],
       [0.21277482, 0.07727116, 0.72708109],
       [0.76522211, 0.25722392, 0.1494935 ]])

In [4]:
# ndarray 속성 : shape, dtype, buffer, offset, strides, order 

print(data.shape) # ndarray각 차원의 크기 
print(data.ndim) # ndarray의 차원 수 OR 배열의 축수
print(data.dtype) # ndarray의 데이터 타입 

(4, 3)
2
float64


In [5]:
print(data.strides)

(24, 8)


#### 2. ndarray 메서드

In [14]:
#  ndarray 생성 메서드 : array(), zeros(), empty(), arrange()...
arr1 = np.zeros(10) # 메모리를 할당받아 0으로 채움 
arr2 = np.empty(10) # 메모리를 할당받지만 0으로 초기화 하진 않음 
print(arr1)
print(arr2)

# empty_like(), zeros_like(), ones_like()... : 입력받은 ndarray와 같은 크기의 ndarray를 만듦

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[nan  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [15]:
# astype() : dtype casting 
arr = np.array([1,2,3,4,5])
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [19]:
# 배열의 산술 연산 
arr = np.array([[1,2,3],[4,5,6]])
arr = arr.astype(np.float64)
arr2 = np.array([[0,4,1],[7,2,12]])

print(arr * arr)
print(arr - arr)
print(arr > arr2)


[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[ True False  True]
 [False  True False]]


In [20]:
# 크기가 다른 배열간의 연산 브로드 캐스팅에 관한 규칙을 따름


#### 3. indexing, slicing 

In [21]:
# ndarray indexing, slicing
list_1 = [1,2,3]
arr_1 = np.array([1,2,3])

# list와 ndarray의 slicing 차이점 
list_2 = list_1[1:]
arr_2 = arr_1[1:]

list_2[0] = 10
arr_2[0] = 10

# list : 값을 복사해서 새로운 리스트를 만듦
print(list_1)
# ndarray : ndarrary의 view를 반환함 
print(arr_1)

[1, 2, 3]
[ 1 10  3]


In [26]:
# boolean indexing 

names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

data = np.random.randn(7,4)
print(data,'\n')
print(names == 'Bob')
data2 = data[names == 'Bob']
data2[0][0] = 100
# boolean indexing 사용시 항상 데이터 복사 발생 
print(data)
print(data2)

[[ 0.91374639  0.47244742 -1.53065624 -0.54199812]
 [ 0.79949144 -1.4226172  -0.86027719  0.32821663]
 [ 0.41392925 -0.01726808  0.73034678 -0.33612221]
 [-0.79135974  0.88985892 -0.23251206  1.44521637]
 [-0.26234701  0.30004479  0.44752536 -0.30134641]
 [ 0.80904368  1.5911659   1.04424558  1.26570203]
 [-1.62565519 -0.11329029 -0.25516578  0.07374234]] 

[ True False False  True False False False]
[[ 0.91374639  0.47244742 -1.53065624 -0.54199812]
 [ 0.79949144 -1.4226172  -0.86027719  0.32821663]
 [ 0.41392925 -0.01726808  0.73034678 -0.33612221]
 [-0.79135974  0.88985892 -0.23251206  1.44521637]
 [-0.26234701  0.30004479  0.44752536 -0.30134641]
 [ 0.80904368  1.5911659   1.04424558  1.26570203]
 [-1.62565519 -0.11329029 -0.25516578  0.07374234]]
[[100.           0.47244742  -1.53065624  -0.54199812]
 [ -0.79135974   0.88985892  -0.23251206   1.44521637]]


In [27]:
# boolean indexing 2

# |, & 연산자 사용 가능 
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [32]:
#  fancy indexing 
arr = np.arange(32).reshape((8,4))
arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

#### 4. 배열 전치, 축 바꾸기 

In [33]:
arr = np.arange(15).reshape(3,5)
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [34]:
# 행렬 내적 구하기 
arr = np.random.randn(6,3)
np.dot(arr.T, arr)

array([[ 8.48074536, -0.14576362, -3.0713202 ],
       [-0.14576362,  5.79989369,  1.6835091 ],
       [-3.0713202 ,  1.6835091 ,  4.99238258]])

In [36]:
# transpose() : 여러개의 축을 한번에 바꿀 수 있음
arr = np.arange(16).reshape((2,2,4))
print(arr, '\n')
print(arr.transpose((1,0,2)))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] 

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [38]:
# swapaxes() : 두개의 축을 바꿀 수 있음 
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

#### 5. universal function

ufunc : ndarray 안에 있는 데이터의 원소별 연산을 수행해주는 함수 


In [39]:
# 단항 유니버셜 함수 : sqrt(), exp() ... 

# 이항 유니버셜 함수 : max()

# 여러 개의 배열을 반환하는 유니버셜 함수 : modf()

#### 6. 배열지향 프로그래밍 

In [41]:
points = np.arange(-5,5,0.01)
xs, ys = np.meshgrid(points,points)

In [42]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [44]:
# np.where() : x if condition else y 
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])
result = [(x if c else y ) for x,y,c in zip(xarr,yarr,cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [45]:
np.where(xarr > 1.3,1,-1)

array([-1, -1, -1,  1,  1])

In [46]:
# 수학 통계 메서드

In [47]:
# 불리언 배열 메서드 

In [ ]:
# 집합 관련 함수 